language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script:
- cd tests && pytest
deploy:
  provider: pypi
  user: 'jfear'
  password:
    secure: "DB2uFxyBj5f1DgTbKOU2RYJamSvc9QmqLzm4g2SD71lULLxVqP4e889g3qiUGH60HGc8hP8ln5VdxPLR2wi5CKFAi0rjfs3UgbBRwVRxcXnAD/jJmpfakMfGJV5TD573THhRJLHsm/2ZTYLZI/XWOfdMr6DnO0P15+oIhnzDAAuEfcW/Xmn+8SD6qa1L+SlD1SJ/s+F/o+HfcRdup2yMIBUw0P7KN5kiNViKWhJMQe8ijpajeoQEmYumSaYgXbPWELzeko+9g8dKB9QFkaBUkdPNFJOAZ3WSM6l16Mzwdd621656yZxmRKRI6qqp6z1Iuqqm4IV8mIgMoffCWp/Ql3di8+osdLFFYpDap6Rqvc0b7N/4MUJCfoAQJJgOo/rseH0HvYJN8jS8Tm+Tmhv2geG/eQXEU/bWHxnNXkW1JAQigIJf9YYPrrXxqxqmKV65Jau+udRV4kNe9Bdc49zqQjSkk+SAH9Yb27A4IA+Xey07EfQDWiyOcAgENl0vuy/jUfNLFTH5bxO9eCP/M0bghlPy2LmviiVWoPh4SRxAUhkFEq87W8MBLFifacuxVF2dAfh7FtfwEHsYEWgQ6hhxcyZYOSDLsveRQXKYVbjB83SkA7byHXVmgm+Ab5Kz6z4bcLEDuvU1Sgp8iL8odr8DQu4E9doxtGU1vA0QJW5KyFM="
  server: https://test.pypi.org/legacy/
  on:
    branch: master
  skip_existing: true
env:
  global:
    secure: ovAgeNA8p6rwCGvlgLaEk6FRhMG9pqBP9WI68osaE2HqidX81NGw5N5yehHNlaVyHLDMXa9wG9szUC6yACCuyjk3TU09u+OnIOrcn4r7DT7hnB+N333hGk4tWZySZ9SREdoZs5+3VKAFawf3rXgZLo62MJhT5ZalxDJrXVpJ7Xw2Vxle5H/WzeB7ZznVbaf1HBrDpIXhJCUCJRnBMACtntsDnYWEett6ZqncVT1ZQO4wWikvyOlnIr/BNRBPsBb4TBNEV3x3e92SkOMjRLbJOgDb1KAEjWF/mCy9yJ07WHM1iumPOCBK1E4wIZAW3j4tqFCucefbpvXxKQTxxubwyiWYmRYLaK7QuoqKQloDdQ4N9Yf7rAviQU7smaPvTqL+cYltf8tscFnuPv5fj6TBgMiXwpyXWXtFxk9CTb34KxSZgo8DVQd0JQ7CrZZm84MthxKCfOTKKsgSXZ3KtzeJxTDHEEz6HchbvL3zt+D02iyyMK6zEDKtaBIX3fyzGcUKD1qCXP59bcBTrDmI1Ylav9WGGHaft01uhm7AgN7qTXhEzPAvY86Y0GCuPft0Px3na/yUgILuUFAaxBRAHK8UMLiZOMGx//GTc54dZpX3U20uHQp/oChZz8WdAHNpyN6xveSCnwh/nEErGPXvTRfk3ibrknHhAfbmMA5+G//EyCM=
