language: python
  - "3.6"
install: bash travis-setup.sh
before_script:
  - export PATH=~/mongo/bin:$PATH
  - export PATH=~/anaconda/bin:$PATH
script:
  - which python
  - python -c 'import sramongo; print(sramongo.__file__)'
  - which mongod
  - mongod --version
  - pytest -v tests
  - ./conda-build-and-upload.sh
  - ./pypi-build-and-upload.sh
