package:
  name: sramongo
  version: 1.1.0
source:
  git_url: https://github.com/jfear/sramongo.git
  git_rev: master

build:
  number: {{ SRAMONGO_BUILD }}

requirements:
  build:
    - python
    - mongoengine >=0.11.0
    - pymongo >=3.3.0
    - pytest >=3.0.5
    - requests >=2.21.0
    - python-dateutil >=2.8.0
    - pytest-runner >=2.11

  run:
    - python
    - mongoengine >=0.11.0
    - pymongo >=3.3.0
    - requests >=2.21.0
    - python-dateutil >=2.8.0
    - pytest >=3.0.5
    - pytest-runner >=2.11

test:
  imports:
    - sramongo

about:
  home: https://github.com/jfear/sramongo
  license: MIT
