package:
  name: sramongo
  version: 1.0.0
source:
  git_url: https://github.com/jfear/sramongo.git
  git_rev: master

build:
  number: {{ SRAMONGO_BUILD }}

requirements:
  build:
    - mongoengine >=0.11.0
    - pymongo >=3.3.0
    - pytest >=3.0.5
    - pytest-runner >=2.11
    - setuptools >=27.2.0
    - sphinx >=1.5.1
    - sphinx_rtd_theme >=0.1.9

  run:
    - mongoengine >=0.11.0
    - pymongo >=3.3.0
    - pytest >=3.0.5
    - pytest-runner >=2.11
    - setuptools >=27.2.0
    - sphinx >=1.5.1
    - sphinx_rtd_theme >=0.1.9

test:
  imports:
    - sramongo

about:
  home: https://github.com/jfear/sramongo
  license: MIT
